src/Form/OpenHoursType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OpenHoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('Monday', DailyTimeSlotType::class)
              ->add('Tuesday', DailyTimeSlotType::class)
              ->add('Wednesday', DailyTimeSlotType::class)
              ->add('Thursday', DailyTimeSlotType::class)
              ->add('Friday', DailyTimeSlotType::class)
              ->add('Saturday', DailyTimeSlotType::class)
              ->add('Sunday', DailyTimeSlotType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
          'data_class' => 'App\Document\OpenHours',
      ]);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'gogo_elementbundle_openhours';
    }
}

templates/bundles/SonataAdminBundle/CRUD/base_edit_form_macro.html.twig
{% macro render_groups(admin, form, groups, has_tab) %}
    <div class="row">

    {% for code in groups if admin.formgroups[code] is defined %}
        {% set form_group = admin.formgroups[code] %}

        <div class="{{ form_group.class|default('col-md-12') }}">
            <div class="{{ form_group.box_class }}">
                <div class="box-header">
                    <h4 class="box-title">
                        {{ form_group.name|trans({}, form_group.translation_domain ?: admin.translationDomain)|raw}}
                    </h4>
                </div>
                <div class="box-body">
                    <div class="sonata-ba-collapsed-fields">
                        {% if form_group.description %}
                            <p>{{ form_group.description|raw }}</p>
                        {% endif %}
                        {% for field_name in form_group.fields if admin.formfielddescriptions[field_name] is defined %}
                            {{ form_row(form[field_name])}}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endmacro %}